site_name: axe-playwright-python
site_description: "axe-playwright-python documentation"
site_author: "Pamela Fox"

# Repository
repo_name: "axe-playwright-python"
repo_url: "https://github.com/pamelafox/axe-playwright-python"

# Copyright
copyright: "Copyright &copy; Ruslan Iskov, Pamela Fox"

theme:
  name: "material"
  language: "en"
  highlightjs: true


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [axe_playwright_python]
          options:
            show_source: false
            heading_level: 2
            show_root_heading: true
            show_root_toc_entry: false
            docstring_section_style: list
            merge_init_into_class: true

# Customization
extra:
  social:
  search:
    language: "en"

nav:
  - About: index.md
  - Usage: usage.md
  - API: api.md
