[tool.poetry]
name = "axe-playwright-python"
version = "0.1.0"
description = "Automated web accessibility testing using axe-core engine and Playwright."
authors = ["Pamela Fox <pamela.fox@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/pamelafox/axe-playwright-python"
documentation = "https://pamelafox.github.io/axe-playwright-python"
keywords = ["accessibility", "axe", "axe-core",  "playwright"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Adaptive Technologies",
    "Topic :: Software Development",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing",
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
black = { version = "^22.6.0", allow-prereleases = true }
playwright = "^1.32.1"
pytest-asyncio = "^0.19.0"
mkdocs = "^1.3.1"
mkdocstrings = {extras = ["python"], version = "^0.19.0"}
mkdocs-material = "^8.4.2"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
